site_url: !ENV [SITE_NAME, 'http://docs.barraider.com']
# do_not_index: true
site_name: BarRaider's Plugin Documentation
markdown_extensions:
  - admonition # Fancy callouts (https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonition-icons)
  - pymdownx.details # Collapsible callouts
  - pymdownx.superfences # Nest Markdown in callouts (https://facelessuser.github.io/pymdown-extensions/extensions/superfences/)
  - pymdownx.keys # Render Keyboard keys with markdown (https://facelessuser.github.io/pymdown-extensions/extensions/keys/)
  - md_in_html # Currently we're using this for image captions
  - pymdownx.tasklist: # Support for Tabs (https://fabacademy.org/2022/labs/kannai/Instruction/tips/tab_in_markdown/)
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - meta # advanced customizable metadata
  - tables
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
plugins:
  - search
  - glightbox #fancy image zoom (https://github.com/blueswen/mkdocs-glightbox#usage)
  - macros
  - mkdocs-video
theme:
  name: "material"
  favicon: "img/favicon.ico"
  custom_dir: overrides
  logo: "img/barraider-logo2.png"
  features:
    - navigation.instant      # Makes it act like a Single-Page Application
    - navigation.tabs         # Top-Level Nav is rendered in the top
    #- navigation.tabs.sticky  # and scrolls with the page on longer pages
    #- navigation.expand      # Show  sub-sections in left pane
    - navigation.indexes      # Simpler Nav for sub-sections with overview pages
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
extra:
  site_short_name: BarRaider Docs
  logo: img/barraider-logo.avif
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback!
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/realBarRaider
    - icon: fontawesome/brands/discord
      link: http://discord.barraider.com/
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/barraider
      name: Support BarRaider's Work on Patreon
    - icon: fontawesome/brands/github
      link: https://github.com/BarRaider
